from __future__ import annotations

import json
import re
from typing import Any
from app.config import GROQ_API_KEY, GROQ_MODEL, USE_GROQ


def _extract_json(text: str) -> dict[str, Any]:
    try:
        return json.loads(text)
    except Exception:
        match = re.search(r"\{.*\}", text, flags=re.S)
        if match:
            return json.loads(match.group(0))
        raise


def mock_llm_json(task: str, payload: dict[str, Any]) -> dict[str, Any]:
    text = payload.get("fnol_text", "").lower()
    product = payload.get("product_type", "motor")
    amount = float(payload.get("claim_amount", 0))
    injury = any(w in text for w in ["injury", "injured", "whiplash", "hospital"])
    storm = "storm" in text or "roof" in text
    water = "water" in text or "leak" in text or "escape" in text
    theft = "theft" in text or "stolen" in text or "burglary" in text

    if task == "triage":
        if product == "motor":
            ctype = "motor_injury" if injury else "motor_accident"
        else:
            ctype = "home_escape_of_water" if water else "home_storm_damage" if storm else "home_theft" if theft else "home_accidental_damage"
        urgency = "high" if injury or amount > 7000 else "medium" if amount > 2000 else "low"
        complexity = "complex" if injury or theft or amount > 6000 else "standard"
        return {
            "claim_type": ctype,
            "incident_summary": payload.get("fnol_text", "")[:350],
            "incident_facts": {
                "injury_reported": injury,
                "loss_cause": ctype,
                "third_party_involved": "third party" in text or "third-party" in text,
                "estimated_amount": amount,
            },
            "urgency": urgency,
            "complexity": complexity,
            "missing_information": ["photos"] if "photo" not in text else [],
            "evidence_required": ["invoice", "photos", "loss report"],
            "confidence": 0.82,
        }
    if task == "coverage":
        return {"coverage_summary": "Coverage may apply subject to policy wording, exclusions, excess, and evidence validation. See cited clauses.", "confidence": 0.75}
    if task == "evidence":
        return {"summary": "Evidence reviewed from available synthetic documents.", "confidence": 0.78}
    if task == "recommendation":
        action = payload.get("allowed_recommended_action", "Manual review required.")
        missing = payload.get("missing_information", [])
        conflicts = payload.get("conflicts", [])
        citations = payload.get("policy_citations", [])
        risk_flags = payload.get("risk_flags", [])
        specialist = bool(payload.get("specialist_review_required"))
        return {
            "recommendation_summary": action,
            "rationale": "This recommendation follows the deterministic route selected from evidence completeness, policy retrieval, and risk screening.",
            "supporting_evidence": ["Retrieved policy clauses are available for handler review."] if citations else [],
            "weakening_evidence": (
                (["Required evidence is missing: " + ", ".join(missing) + "."] if missing else [])
                + (["Conflicting evidence requires clarification."] if conflicts else [])
                + (["Risk flags are present: " + ", ".join(risk_flags) + "."] if risk_flags else [])
            ),
            "relevant_policy_clauses": [
                f"{c.get('source_file') or 'policy'} / {c.get('section') or c.get('chunk_id') or 'clause'}"
                for c in citations
            ],
            "customer_questions": (
                (["Please provide the missing evidence before the claim progresses."] if missing else [])
                + (["Please confirm the correct incident date and explain the discrepancy."] if conflicts else [])
            ),
            "missing_documents_to_request": missing,
            "specialist_review_needed": specialist,
            "specialist_review_reason": "Risk screening requires fraud or specialist review." if specialist else "",
            "confidence": 0.76,
        }
    return {"summary": "Generated by mock model", "confidence": 0.7}


def call_llm_json(system_prompt: str, user_payload: dict[str, Any], task: str) -> dict[str, Any]:
    if not USE_GROQ:
        return mock_llm_json(task, user_payload)

    from groq import Groq

    client = Groq(api_key=GROQ_API_KEY)
    user_prompt = json.dumps(user_payload, indent=2)
    response = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0.1,
        response_format={"type": "json_object"},
    )
    return _extract_json(response.choices[0].message.content or "{}")
